#!/bin/bash
#set -x
STACK_PATH=$(pwd)

echo "DB1 Global Software - DB1 Stack Observability SRE"

COMPONENT=$STACK_PATH/$1


if [ "$#" -lt 1 ]; then
    echo ""
    echo "Por favor, forneça o paramêtro!"
    echo ""
    echo "1. db1@stack$ ./db1-stack elk"
    echo "2. db1@stack$ ./db1-stack elk up -d"
    echo ""
    echo "1. db1@stack$ ./db1-stack mon"
else
    if [ ! -d $COMPONENT ]; then
        echo -e "\033[0;31mComponent \"$COMPONENT\" does not exists." >&2
        exit 1
    else
        if [ "$1" = "elk" ]; then
            CMD=${@:2}
            docker compose -f $COMPONENT/docker-compose.yml ${CMD:-up setup}
        elif [ "$1" = "mon" ]; then
            docker compose -f $COMPONENT/docker-compose.yml up -d
            echo "Install Sucessfully - Monitoring!"

        fi
    fi
fi
